[features]
seeds = false
skip-lint = false


[workspace]
members = [
  "programs/vehicle_node_chain",
  "programs/platoon_manager",
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
vehicle_node_chain = ""
platoon_manager = ""





